import json
import random

random.seed(42)

products = []
pid = 1

# ---- Electronics ----
electronics = [
    ("Wireless Bluetooth Headphones", 79.99, 4.5, "Noise-cancelling with 30hr battery life."),
    ("4K Ultra HD Monitor 27\"", 449.99, 4.6, "IPS panel, USB-C, 60Hz, HDR400."),
    ("Mechanical Keyboard RGB", 129.99, 4.8, "Cherry MX switches, hot-swappable, programmable."),
    ("USB-C Hub 7-in-1", 34.99, 4.1, "HDMI 4K, SD card reader, 100W PD passthrough."),
    ("Smartphone 128GB", 699.99, 4.7, "6.5\" AMOLED, 5G, triple camera system."),
    ("Wireless Mouse Ergonomic", 49.99, 4.4, "4000 DPI, USB-C rechargeable, 6 buttons."),
    ("Portable Bluetooth Speaker", 59.99, 4.3, "Waterproof IPX7, 20hr battery, deep bass."),
    ("USB-C Charging Cable 6ft", 9.99, 4.6, "Braided nylon, 100W fast charge, 3-pack."),
    ("Laptop Stand Adjustable", 39.99, 4.5, "Aluminum, fits 10-17\", ventilated design."),
    ("Webcam 1080p HD", 44.99, 4.2, "Auto-focus, built-in mic, privacy cover."),
    ("External SSD 1TB", 109.99, 4.8, "USB 3.2, 1050MB/s read, portable."),
    ("Smartwatch Pro", 249.99, 4.6, "GPS, heart rate, SpO2, 7-day battery."),
    ("Tablet 10.5\" 64GB", 329.99, 4.4, "Wi-Fi 6, 1080p display, 12hr battery."),
    ("Wireless Charging Pad", 19.99, 4.3, "Qi-compatible, 15W fast charge, LED indicator."),
    ("Noise Cancelling Earbuds", 149.99, 4.7, "Active NC, IPX5, 8hr + case."),
    ("Gaming Mouse RGB", 69.99, 4.5, "16000 DPI, 8 programmable buttons, lightweight."),
    ("Desktop Microphone USB", 79.99, 4.4, "Cardioid, mute button, gain control."),
    ("Portable Power Bank 20000mAh", 35.99, 4.6, "USB-C in/out, fast charge, LCD display."),
    ("Smart Plug WiFi", 14.99, 4.2, "Alexa/Google compatible, energy monitoring."),
    ("Wireless Router WiFi 6", 129.99, 4.5, "AX3000, dual-band, 4 gigabit ports."),
    ("Dash Cam 4K", 89.99, 4.3, "Wide angle, night vision, loop recording."),
    ("Fitness Tracker Band", 39.99, 4.1, "Step counter, sleep tracker, heart rate."),
    ("LED Strip Lights 16ft", 18.99, 4.4, "RGB, app controlled, music sync."),
    ("Smart Thermostat", 119.99, 4.6, "WiFi, programmable, energy saving."),
    ("Computer Speakers 2.0", 34.99, 4.2, "USB powered, 3.5mm aux, volume control."),
    ("Graphic Drawing Tablet", 199.99, 4.5, "8192 pressure levels, wireless, 10x6\""),
    ("VR Headset", 399.99, 4.3, "Standalone, 4K display, 6DOF tracking."),
    ("Action Camera 4K", 249.99, 4.4, "Waterproof 10m, stabilization, wide angle."),
    ("Smart Doorbell Camera", 99.99, 4.2, "1080p, two-way audio, motion detection."),
    ("Security Camera Indoor", 45.99, 4.3, "360° pan/tilt, night vision, microSD."),
    ("Bluetooth GPS Tracker", 24.99, 4.1, "Find keys/wallet, 1yr battery, app."),
    ("Car Phone Mount", 15.99, 4.4, "Magnetic, air vent, 360° rotation."),
    ("HDMI Cable 6ft 4K", 8.99, 4.7, "48Gbps, HDMI 2.1, braided."),
    ("Smart Light Bulb WiFi", 12.99, 4.3, "RGBWW, dimmable, app controlled."),
    ("CPU Cooler RGB", 49.99, 4.5, "Tower design, 120mm fan, copper base."),
    ("Graphics Card RTX 5070", 799.99, 4.8, "16GB GDDR7, ray tracing, DLSS 4."),
    ("Power Supply 750W", 109.99, 4.6, "80+ Gold, modular, silent fan."),
    ("RAM 32GB DDR5", 89.99, 4.7, "5600MHz, RGB, dual channel kit."),
    ("Motherboard Z890", 279.99, 4.5, "LGA 1851, DDR5, PCIe 5.0, WiFi 7."),
    ("SSD 2TB NVMe", 149.99, 4.8, "7000MB/s read, PCIe 4.0, heatsink."),
    ("Projector 1080p", 259.99, 4.2, "4500 lumens, 120\" screen, built-in speaker."),
    ("Digital Photo Frame", 79.99, 4.1, "15.6\", 1080p, WiFi upload, 16GB."),
    ("E-Reader 6\"", 119.99, 4.5, "300 PPI, backlit, waterproof, 8GB."),
    ("Portable Monitor 15.6\"", 199.99, 4.4, "1080p, USB-C, built-in stand."),
    ("Video Capture Card", 59.99, 4.3, "4K pass-through, USB 3.0, low latency."),
    ("Stream Deck Mini", 49.99, 4.6, "6 LCD keys, customizable, OBS support."),
    ("Solder Station Digital", 69.99, 4.2, "Adjustable temp, sleep mode, 60W."),
    ("Multimeter Digital", 29.99, 4.4, "Auto-ranging, backlight, NCV detection."),
    ("Raspberry Pi 5 8GB", 79.99, 4.7, "Quad-core, WiFi, Bluetooth 5.0."),
    ("Arduino Starter Kit", 44.99, 4.5, "Uno R3, 15 projects, components included."),
    ("Drone with Camera", 199.99, 4.1, "1080p, 30min flight, GPS return."),
    ("Mini Projector", 89.99, 4.0, "Portable, 720p, battery, HDMI/USB."),
    ("Electric Toothbrush", 49.99, 4.5, "Sonic, 5 modes, 2-week battery."),
    ("Hair Dryer Ionic", 34.99, 4.3, "1800W, 3 heat settings, diffuser."),
    ("Electric Shaver Foil", 69.99, 4.4, "Wet/dry, pop-up trimmer, LED display."),
    ("Robot Vacuum Cleaner", 299.99, 4.5, "LiDAR mapping, 2500Pa, app control."),
    ("Air Purifier HEPA", 149.99, 4.6, "Covers 500sqft, quiet, auto mode."),
    ("Humidifier Ultrasonic", 39.99, 4.3, "2.5L tank, quiet, auto shut-off."),
    ("Space Heater Ceramic", 44.99, 4.2, "1500W, tip-over protection, thermostat."),
]
for name, price, rating, desc in electronics:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Electronics", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Home & Kitchen ----
home_kitchen = [
    ("Stainless Steel Water Bottle", 24.99, 4.7, "Double-wall insulated, 750ml, 24hr cold."),
    ("Cast Iron Skillet 12\"", 44.99, 4.9, "Pre-seasoned, oven-safe 500F."),
    ("Weighted Blanket 15lbs", 69.99, 4.6, "Cotton cover, glass bead fill, machine washable."),
    ("Non-Stick Frying Pan Set", 59.99, 4.5, "3-piece, aluminum core, dishwasher safe."),
    ("Stainless Steel Cookware Set", 199.99, 4.7, "10-piece, induction compatible, oven-safe."),
    ("Kitchen Knife Block Set", 89.99, 4.6, "8 knives, stainless steel, ergonomic handles."),
    ("Cutting Board Bamboo", 24.99, 4.4, "Large 18x12\", knife-friendly, juice groove."),
    ("Dutch Oven 6qt", 79.99, 4.8, "Enameled cast iron, self-basting lid."),
    ("Coffee Maker 12-Cup", 49.99, 4.4, "Programmable, thermal carafe, auto shut-off."),
    ("Espresso Machine", 149.99, 4.5, "15 bar pump, milk frother, single/double shot."),
    ("Blender 1000W", 59.99, 4.6, "BPA-free jar, 6 blades, variable speed."),
    ("Air Fryer 5.8qt", 79.99, 4.7, "Digital touch, 8 presets, rapid air circulation."),
    ("Instant Pot 6qt", 89.99, 4.8, "9-in-1 pressure cooker, slow cooker, rice cooker."),
    ("Toaster 2-Slice", 29.99, 4.3, "Wide slots, 6 settings, self-centering."),
    ("Stand Mixer 5qt", 249.99, 4.7, "Tilt-head, 10 speeds, dough hook included."),
    ("Food Processor 14-Cup", 119.99, 4.5, "S-blade, slicing/shredding discs, extra-large feed."),
    ("Electric Kettle 1.7L", 29.99, 4.6, "Stainless steel, auto shut-off, rapid boil."),
    ("Slow Cooker 6qt", 39.99, 4.4, "3 heat settings, programmable timer, lid lock."),
    ("Rice Cooker 10-Cup", 44.99, 4.5, "Fuzzy logic, keep warm, steaming basket."),
    ("Knife Sharpener Manual", 14.99, 4.2, "Two-stage, diamond rods, non-slip base."),
    ("Measuring Cups Set", 12.99, 4.6, "Stainless steel, 6 pieces, nesting design."),
    ("Mixing Bowls Set", 19.99, 4.5, "5 pieces, glass, pour spouts, lids."),
    ("Baking Sheet Set", 24.99, 4.4, "3 sizes, non-stick, heavy gauge steel."),
    ("Silicone Spatula Set", 11.99, 4.5, "3 sizes, heat-resistant 600F, one-piece."),
    ("Tongs Kitchen 9\"", 9.99, 4.3, "Stainless steel, silicone tips, locking."),
    ("Pots and Pans Set 8pc", 129.99, 4.5, "Granite coating, soft-touch handles."),
    ("Wok 14\" Carbon Steel", 39.99, 4.6, "Flat bottom, riveted handle, pre-seasoned."),
    ("Chef's Knife 8\"", 49.99, 4.7, "German steel, full tang, ergonomic handle."),
    ("Paring Knife 3.5\"", 19.99, 4.4, "High-carbon stainless, precision tip."),
    ("Bread Knife 10\"", 24.99, 4.4, "Serrated edge, offset handle, stainless."),
    ("Peeler Swivel", 5.99, 4.3, "Stainless blade, ergonomic grip, dishwash safe."),
    ("Grater Box 4-Sided", 12.99, 4.5, "Stainless steel, fine/coarse/slicing, container."),
    ("Colander Stainless 5qt", 16.99, 4.4, "Fine mesh, sturdy base, hanging loop."),
    ("Strainer Fine Mesh 3\"", 7.99, 4.2, "Mini, stainless, heat-resistant handle."),
    ("Can Opener Handheld", 8.99, 4.3, "Smooth edge, no sharp lids, easy turn."),
    ("Garlic Press Stainless", 9.99, 4.4, "Curved handles, self-cleaning, easy squeeze."),
    ("Vegetable Chopper", 19.99, 4.5, "Multi-blade, container catches, dicer/slicer."),
    ("Mandoline Slicer Adjustable", 29.99, 4.3, "Julienne, straight cut, thickness dial."),
    ("Salad Spinner 5qt", 24.99, 4.4, "Push-button brake, non-slip base, clear bowl."),
    ("Food Scale Digital", 14.99, 4.6, "5kg capacity, tare, LCD, auto-off."),
    ("Thermometer Meat Probe", 18.99, 4.5, "Instant read, backlight, magnet back."),
    ("Cooking Timer Magnetic", 7.99, 4.3, "Digital, count up/down, strong magnet."),
    ("Salt and Pepper Grinder Set", 24.99, 4.5, "Ceramic burr, adjustable coarseness."),
    ("Oil Dispenser 17oz", 11.99, 4.2, "Glass bottle, pour spout, drip-free."),
    ("Tea Infuser Bottle 20oz", 14.99, 4.4, "BPA-free, built-in infuser, leak-proof."),
    ("French Press 34oz", 29.99, 4.5, "Borosilicate glass, stainless plunger, 8-cup."),
    ("Pour Over Coffee Maker", 19.99, 4.4, "Ceramic, cone filter, single serve."),
    ("Milk Frother Handheld", 12.99, 4.3, "Battery operated, stainless whisk."),
    ("Wine Opener Electric", 34.99, 4.5, "Rechargeable, foil cutter, auto operation."),
    ("Corkscrew Waiter Style", 9.99, 4.4, "Double hinged, serrated foil cutter."),
    ("Vacuum Sealer Machine", 49.99, 4.4, "Automatic, bag cutter, included rolls."),
    ("Food Storage Container Set", 29.99, 4.6, "20 pieces, BPA-free, airtight, microwave."),
    ("Glass Meal Prep Containers", 24.99, 4.5, "6-pack, 3-compartment, leak-proof lids."),
    ("Ice Cube Tray Silicone", 8.99, 4.4, "2-pack, flexible, 60 cubes total."),
    ("Water Filter Pitcher", 34.99, 4.5, "10-cup, reduces chlorine, 1 filter included."),
    ("Bottle Opener Wall Mount", 7.99, 4.3, "Heavy duty, magnetic cap catcher."),
    ("Pizza Cutter 4\"", 6.99, 4.4, "Stainless blade, ergonomic handle, blade guard."),
    ("Microplane Zester", 11.99, 4.6, "Stainless steel, fine edge, non-slip handle."),
    ("Mortar and Pestle", 19.99, 4.4, "Granite, 2-cup capacity, natural stone."),
    ("Rolling Pin Wooden", 14.99, 4.3, "Straight, tapered ends, 18\" long."),
    ("Pastry Brush Silicone", 6.99, 4.2, "Heat resistant 600F, 2-pack."),
    ("Cooling Rack Baking", 12.99, 4.4, "Set of 2, non-stick, stackable."),
    ("Muffin Pan 12-Cup", 14.99, 4.4, "Non-stick, heavy gauge steel."),
    ("Loaf Pan 9x5\"", 11.99, 4.3, "Carbon steel, non-stick, even baking."),
    ("Cake Pan Round 9\"", 9.99, 4.4, "Aluminum, 2-pack, straight sides."),
    ("Piping Bag Set", 8.99, 4.3, "12 disposable bags, 8 tips, couplers."),
    ("Cookie Sheet 13x18\"", 16.99, 4.5, "Aluminized steel, non-stick, rimmed."),
    ("Saucepan 2qt", 29.99, 4.5, "Stainless, tri-ply, tempered lid."),
    ("Stockpot 8qt", 39.99, 4.6, "Stainless, heavy bottom, pasta insert."),
    ("Sauté Pan 12\"", 44.99, 4.5, "Non-stick, helper handle, glass lid."),
    ("Griddle 20\"", 34.99, 4.4, "Non-stick, dual burner, pour spout."),
    ("Electric Griddle 15\"", 44.99, 4.5, "Temp control, non-stick, dishwasher safe."),
    ("Waffle Maker Belgian", 39.99, 4.6, "Rotating, 5 browning levels, non-stick."),
    ("Panini Press", 34.99, 4.4, "Floating hinge, non-stick, indicator lights."),
    ("Toaster Oven 4-Slice", 69.99, 4.5, "Digital, air fry mode, convection."),
    ("Microwave 0.7cuft", 79.99, 4.4, "700W, digital, 10 power levels."),
    ("Hand Mixer 5-Speed", 29.99, 4.5, "Beaters, dough hooks, storage case."),
    ("Immersion Blender", 34.99, 4.4, "Stainless shaft, 2 speeds, whisk attachment."),
    ("Pressure Cooker Stovetop 6qt", 69.99, 4.6, "Aluminum, dual pressure, locking lid."),
    ("Steamer Basket 9\"", 7.99, 4.3, "Stain steel, foldable, fits 8-10qt pots."),
    ("Measuring Spoon Set", 7.99, 4.5, "Stainless, 8 pieces, magnetic ring."),
    ("Liquid Measuring Cup Glass", 9.99, 4.5, "4-cup, etched markings, microwave safe."),
    ("Glass Mixing Bowl Set", 21.99, 4.5, "3 sizes, pour spout, nesting storage."),
]
for name, price, rating, desc in home_kitchen:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Home & Kitchen", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Furniture ----
furniture = [
    ("Ergonomic Office Chair", 349.99, 4.3, "Adjustable lumbar, mesh back, 5yr warranty."),
    ("Smart LED Desk Lamp", 59.99, 4.3, "Wireless charging, 5 color modes."),
    ("Standing Desk Electric", 499.99, 4.6, "Height adjustable 28-48\", memory presets."),
    ("Bookshelf 5-Tier", 89.99, 4.4, "Engineered wood, open back, 60\" tall."),
    ("Desk 55x24\"", 179.99, 4.4, "Rectangular, wood finish, metal legs."),
    ("Office Chair Mesh", 219.99, 4.5, "High back, flip-up armrests, tilt lock."),
    ("File Cabinet 2-Drawer", 119.99, 4.3, "Letter size, lockable, steel ball bearings."),
    ("Monitor Stand Riser", 34.99, 4.4, "Bamboo, 2-tier, storage shelf underneath."),
    ("Under Desk Drawer", 29.99, 4.3, "Sliding, pen tray, easy mount."),
    ("Ergonomic Foot Rest", 24.99, 4.2, "Adjustable angle, massage surface."),
    ("Lumbar Support Cushion", 19.99, 4.4, "Breathable mesh, adjustable straps."),
    ("Desk Organizer 5-Compartment", 15.99, 4.3, "Bamboo, mail slot, pen holder."),
    ("Sofa 3-Seater", 599.99, 4.4, "Fabric upholstery, removable cushions."),
    ("Coffee Table 40x20\"", 149.99, 4.3, "Wood, lower shelf, modern design."),
    ("TV Stand 55\"", 219.99, 4.4, "Media console, cable management, 2 drawers."),
    ("End Table 24\"", 79.99, 4.2, "Solid wood, storage shelf, nightstand."),
    ("Recliner Chair Single", 399.99, 4.5, "Push-back reclining, padded armrests."),
    ("Rocking Chair Wooden", 179.99, 4.3, "Solid oak, curved runners, padded seat."),
    ("Bookshelf Ladder 8-Tier", 129.99, 4.3, "Leaning, metal frame, wood shelves."),
    ("Entryway Bench 42\"", 169.99, 4.2, "Padded seat, shoe storage underneath."),
    ("Coat Rack Free Standing", 39.99, 4.3, "Metal, 8 hooks, heavy base."),
    ("Shoe Rack 10-Tier", 34.99, 4.4, "Steel, holds 20 pairs, assembly required."),
    ("Bed Frame Queen", 249.99, 4.5, "Metal platform, no box spring needed."),
    ("Mattress Queen 10\"", 349.99, 4.6, "Memory foam, medium firmness, cooling gel."),
    ("Pillow Set Queen", 39.99, 4.4, "2-pack, microfiber, hypoallergenic."),
    ("Comforter Set Queen", 59.99, 4.5, "7-piece, microfiber, all-season."),
    ("Sheet Set Queen 4pc", 29.99, 4.5, "1800 thread count, deep pocket."),
    ("Mattress Topper 3\"", 79.99, 4.4, "Memory foam, cooling, queen size."),
    ("Bedside Table 20\"", 89.99, 4.3, "Solid wood, 1 drawer, USB charging."),
    ("Dresser 6-Drawer", 299.99, 4.4, "Wood, fabric bins, metal frame."),
    ("Closet Organizer System", 79.99, 4.2, "Adjustable shelves, hanging rod, 5ft."),
    ("Wardrobe Armoire 60\"", 349.99, 4.3, "Freestanding, 2 doors, hanging rod."),
    ("Mirror Full Length 60\"", 44.99, 4.3, "Floor leaning, aluminum frame."),
    ("Wall Shelf Set 3-Pack", 29.99, 4.3, "Floating, 16\", 20\", 24\", black."),
    ("Floating Shelves 6-Pack", 39.99, 4.4, "12\", 16\", 20\", heavy duty brackets."),
    ("Corner Shelf 5-Tier", 49.99, 4.2, "Triangular, wood, display/storage."),
    ("Wine Rack 12-Bottle", 34.99, 4.3, "Countertop, wood, slotted design."),
    ("Bar Stool Set 2", 129.99, 4.3, "Counter height, padded seat, footrest."),
    ("Dining Table 60\"", 449.99, 4.5, "Solid wood, seats 6-8, expandable."),
    ("Dining Chair Set 4", 199.99, 4.4, "Padded seat, wood frame, modern."),
    ("Kitchen Island with Storage", 299.99, 4.4, "Butcher block top, shelves, towel bar."),
    ("Kitchen Cart Portable", 119.99, 4.3, "Stainless top, locking wheels."),
    ("Bathroom Vanity 36\"", 249.99, 4.3, "White, ceramic sink, soft-close doors."),
    ("Medicine Cabinet 30\"", 79.99, 4.2, "Mirrored door, adjustable shelves."),
    ("Towel Rack 24\"", 24.99, 4.3, "Stainless steel, 2 bars, wall mount."),
    ("Toilet Paper Holder", 12.99, 4.2, "Brushed nickel, spring loaded."),
    ("Shower Caddy Corner", 19.99, 4.3, "Stainless, rust proof, 5 shelves."),
    ("Bath Mat Memory Foam", 18.99, 4.4, "Soft, absorbent, non-slip rubber."),
    ("Shower Curtain Liner", 9.99, 4.2, "PEVA, 12 hooks, mildew resistant."),
    ("Trash Can 13gal Touch", 39.99, 4.4, "Stainless, motion sensor, odor filter."),
    ("Laundry Hamper 2-Compartment", 29.99, 4.3, "Collapsible, handles, 60L total."),
    ("Drying Rack Foldable", 24.99, 4.4, "Accordion, 45\" drying space."),
    ("Ironing Board 54x15\"", 34.99, 4.3, "Padded cover, adjustable height."),
    ("Steam Iron 1500W", 29.99, 4.4, "Ceramic soleplate, anti-drip, self-clean."),
    ("Storage Ottoman 36\"", 69.99, 4.4, "Faux leather, storage inside, tufted top."),
    ("Futon Sofa Bed", 249.99, 4.3, "Convertible, memory foam, 3 positions."),
    ("Bean Bag Chair 5ft", 79.99, 4.2, "Microsuede, memory foam fill, removable."),
    ("Floor Lamp 60\"", 49.99, 4.3, "LED dimmable, reading, modern design."),
    ("Table Lamp Set 2", 44.99, 4.2, "Ceramic base, fabric shade, 26\"."),
    ("Ceiling Fan 52\"", 129.99, 4.5, "LED, remote, reversible, 6 speeds."),
    ("Desk Fan 10\"", 24.99, 4.2, "Quiet, oscillating, 3 speeds."),
    ("Pedestal Fan 16\"", 34.99, 4.3, "Remote, oscillation, adjustable height."),
    ("Tower Fan 36\"", 59.99, 4.4, "Bladeless, remote, DC motor, quiet."),
    ("Electric Fireplace Heater", 139.99, 4.3, "Flame effect, remote, 1500W."),
    ("Dehumidifier 50pt", 199.99, 4.5, "Covers 3000sqft, auto shut-off."),
    ("Humidifier Cool Mist 6L", 49.99, 4.4, "Ultrasonic, essential oil tray, top fill."),
    ("Air Circulator Fan", 44.99, 4.3, "Powerful, vortex, 8 speeds."),
    ("Portable Air Conditioner", 349.99, 4.4, "10000 BTU, remote, window kit."),
    ("Heater Space 1500W", 39.99, 4.3, "Ceramic, oscillating, safety shut-off."),
    ("Honey Jar with Dipper", 11.99, 4.2, "Ceramic, 12oz, wooden honey stick."),
    ("Butter Dish with Lid", 9.99, 4.3, "Ceramic, holds 1 stick, microwave safe."),
    ("Sugar Bowl with Lid", 8.99, 4.2, "Porcelain, 8oz, spoon included."),
    ("Salt Pig Clay", 7.99, 4.1, "Handmade, natural clay, holds 1 cup."),
    ("Napkin Rings Set 6", 12.99, 4.2, "Stainless steel, brushed finish."),
    ("Table Runner 72\"", 14.99, 4.3, "Linen blend, farmhouse style."),
    ("Placemat Set 6", 18.99, 4.3, "Bamboo, heat resistant, easy clean."),
    ("Coaster Set 8", 14.99, 4.4, "Slate stone, cork bottom, holder."),
    ("Wine Decanter 25oz", 29.99, 4.4, "Crystal glass, hand blown, aerating."),
    ("Cheese Board Set", 34.99, 4.5, "Marble, 4 cheese knives, serving."),
    ("Serving Platter 16\"", 24.99, 4.3, "Melamine, fish shape, dishwasher safe."),
    ("Pitcher Glass 64oz", 16.99, 4.3, "Borosilicate, lid, pour spout."),
    ("Ice Bucket with Tongs", 22.99, 4.2, "Stainless, insulated, 3L capacity."),
    ("Cake Stand Rotating", 24.99, 4.4, "Ceramic, turntable, 10\" diameter."),
    ("Candy Dish with Lid", 12.99, 4.2, "Glass, crystal cut, 8\"."),
    ("Bread Box 18\"", 34.99, 4.3, "Bamboo, roll-top lid, holds 2 loaves."),
    ("Fruit Bowl 10\"", 18.99, 4.3, "Ceramic, footed, dishwasher safe."),
    ("Trivet 3-Pack", 14.99, 4.4, "Silicone, heat resistant 450F."),
    ("Oven Mitt Set 2", 12.99, 4.4, "Silicone, 500F protection, quilted."),
    ("Apron Kitchen Premium", 19.99, 4.3, "Cotton, adjustable, 2 pockets."),
    ("Dish Drying Mat 17x14\"", 11.99, 4.4, "Microfiber, absorbent, non-slip."),
    ("Sink Caddy 2-Compartment", 9.99, 4.2, "Stainless, rust-resistant, drain."),
    ("Sponge Holder with Drain", 6.99, 4.3, "Ceramic, whale shape, countertop."),
    ("Dish Soap Dispenser 16oz", 9.99, 4.3, "Glass, pump, stainless handle."),
    ("Paper Towel Holder", 12.99, 4.3, "Stainless, weighted base, countertop."),
    ("Trash Can 4gal Stainless", 24.99, 4.4, "Step pedal, removable liner."),
    ("Recycling Bin 2-Compartment", 29.99, 4.3, "Plastic, 14gal total, labels."),
]
for name, price, rating, desc in furniture:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Furniture", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Sports & Fitness ----
sports = [
    ("Yoga Mat Premium 6mm", 39.99, 4.2, "Non-slip, eco-friendly TPE, carrying strap."),
    ("Running Shoes Men's", 119.99, 4.5, "Lightweight mesh, responsive cushioning."),
    ("Dumbbell Set 20lbs", 49.99, 4.4, "Neoprene, 2x10lbs, hex shape."),
    ("Adjustable Dumbbells 5-52.5lbs", 349.99, 4.7, "Space saving, quick change, stand included."),
    ("Kettlebell 35lbs", 39.99, 4.5, "Cast iron, flat base, powder coat."),
    ("Barbell 45lbs Olympic", 149.99, 4.6, "7ft, 1500lb capacity, knurled grip."),
    ("Weight Bench Adjustable", 199.99, 4.5, "Incline/flat/decline, 800lb capacity."),
    ("Resistance Bands Set", 24.99, 4.4, "5 levels, door anchor, carry bag."),
    ("Jump Rope Speed", 14.99, 4.3, "Ball bearing, adjustable, foam handles."),
    ("Foam Roller 18\"", 19.99, 4.4, "High density, muscle recovery, trigger point."),
    ("Yoga Block Set 2", 11.99, 4.3, "EVA foam, non-slip, rounded edges."),
    ("Yoga Strap 8ft", 9.99, 4.2, "Cotton, D-ring buckle, carrying loop."),
    ("Exercise Ball 65cm", 24.99, 4.3, "Anti-burst, pump included, 2200lb max."),
    ("Pull Up Bar Doorway", 39.99, 4.5, "Install-free, 3 grip positions, foam pads."),
    ("Push Up Stands Pair", 19.99, 4.3, "Padded handles, non-slip base, rotating."),
    ("Ab Roller Knee Pad", 14.99, 4.2, "Dual wheel, padded knee mat."),
    ("Treadmill Folding", 599.99, 4.5, "2.5HP, incline, 12 programs, folding."),
    ("Exercise Bike Stationary", 299.99, 4.4, "Magnetic resistance, LCD, adjustable."),
    ("Rowing Machine Air", 449.99, 4.5, "Air resistance, folding, monitor."),
    ("Elliptical Machine", 499.99, 4.3, "Magnetic, 16 levels, pulse sensors."),
    ("Recumbent Bike", 349.99, 4.4, "Comfort seat, back support, 8 programs."),
    ("Step Platform Adjustable", 44.99, 4.2, "Height adjustable 4-8\", non-slip."),
    ("Boxing Gloves 12oz", 34.99, 4.5, "Leather, wrist support, breathable palm."),
    ("Punching Bag 70lbs", 89.99, 4.4, "Heavy bag, hanging straps, filled."),
    ("Hand Wraps 180\"", 9.99, 4.4, "Cotton, elastic, velcro closure, pair."),
    ("Speed Bag Platform", 59.99, 4.2, "Mounted, adjustable height, swivel."),
    ("Boxing Stand Free Standing", 199.99, 4.3, "Height adjustable 5-7ft, water base."),
    ("Yoga Towel 72\"x26\"", 18.99, 4.2, "Microfiber, non-slip, machine washable."),
    ("Gym Bag 30L", 34.99, 4.3, "Waterproof, shoe compartment, USB port."),
    ("Water Bottle Shaker 28oz", 12.99, 4.3, "BPA-free, mixing ball, leak-proof."),
    ("Protein Shaker Bottle 20oz", 9.99, 4.2, "Flip lid, mixing grid, measurement marks."),
    ("Sweat Towel 24x48\"", 8.99, 4.2, "Microfiber, quick dry, pack of 3."),
    ("Workout Gloves Fingerless", 19.99, 4.3, "Leather palm, gel padding, wrist wrap."),
    ("Weightlifting Belt Leather", 39.99, 4.4, "4\" wide, double prong, suede."),
    ("Knee Sleeves Pair", 29.99, 4.4, "Neoprene, 7mm thick, compression."),
    ("Wrist Wraps Pair", 14.99, 4.3, "Elastic, thumb loop, 12\" long."),
    ("Headband Sweatband", 7.99, 4.2, "Terry cloth, 3-pack, adjustable."),
    ("Running Belt Waist Pack", 14.99, 4.3, "Elastic, phone pocket, reflective."),
    ("Hydration Vest 5L", 49.99, 4.4, "BPA-free bladder, multiple pockets."),
    ("Running Hat Lightweight", 19.99, 4.3, "Moisture wicking, UPF 50, breathable."),
    ("Trail Running Poles", 69.99, 4.3, "Carbon fiber, cork grip, 2 sections."),
    ("Camping Tent 4-Person", 149.99, 4.5, "Waterproof, easy setup, 3-season."),
    ("Sleeping Bag 20°F", 69.99, 4.4, "Mummy, synthetic fill, compression sack."),
    ("Camping Stove 2-Burner", 59.99, 4.4, "Propane, 20000 BTU, windscreen."),
    ("Cooler 45qt Rotomolded", 149.99, 4.6, "Bear resistant, 5-day ice retention."),
    ("Hiking Backpack 50L", 89.99, 4.5, "Internal frame, rain cover, hydration."),
    ("Headlamp 1000 Lumens", 34.99, 4.5, "Rechargeable, waterproof, motion sensor."),
    ("Camping Chair Padded", 39.99, 4.3, "250lb capacity, cup holder, carry bag."),
    ("Hammock Double", 34.99, 4.4, "Parachute nylon, tree straps included."),
    ("Portable Grill Tabletop", 44.99, 4.3, "Charcoal, adjustable air vent, 150sqin."),
    ("Water Filter Bottle 24oz", 29.99, 4.4, "Filter 99.9% bacteria, BPA-free."),
    ("Sunglasses Polarized", 24.99, 4.3, "UV400, polycarbonate, lightweight."),
    ("Baseball Cap Classic", 14.99, 4.2, "Cotton twill, adjustable back."),
    ("Basketball Outdoor", 24.99, 4.4, "Rubber, size 7, durable compound."),
    ("Soccer Ball Size 5", 19.99, 4.4, "PU leather, stitched, match quality."),
    ("Football Official Size", 29.99, 4.3, "Leather, composite grip., laces."),
    ("Volleyball Beach", 24.99, 4.3, "PVC, soft touch, waterproof."),
    ("Tennis Racket Strung", 59.99, 4.4, "Aluminum frame, grip 4 3/8\","),
    ("Badminton Racket Set 2", 34.99, 4.3, "Steel frame, nylon strings, covers."),
    ("Table Tennis Paddle Set 2", 29.99, 4.3, "ITTF approved, rubber, case."),
    ("Pickleball Paddle Set 4", 59.99, 4.4, "Fiberglass, foam core, 4 balls."),
    ("Golf Club Set Men's 10pc", 299.99, 4.5, "Driver, irons, putter, stand bag."),
    ("Golf Balls 12-Pack", 24.99, 4.4, "Surlyn cover, 2-piece, distance."),
    ("Golf Glove Synthetic", 12.99, 4.3, "Cabretta leather, velcro, men's."),
    ("Golf Towel 15x24\"", 11.99, 4.2, "Microfiber, carabiner clip."),
    ("Disc Golf Disc Set 3", 24.99, 4.3, "Driver, mid-range, putter."),
    ("Frisbee Ultimate 175g", 14.99, 4.3, "Regulation size, durable plastic."),
    ("Skateboard Complete", 59.99, 4.4, "Maple deck, ABEC 7 bearings."),
    ("Longboard 42\"", 89.99, 4.4, "Bamboo deck, reverse kingpin trucks."),
    ("Roller Skates Adjustable", 49.99, 4.3, "Quad, brake, ABEC 7, padded."),
    ("Kick Scooter Foldable", 44.99, 4.2, "Aluminum, adjustable height, 220lb."),
    ("Electric Scooter 15mph", 399.99, 4.4, "25mi range, 10\" tires, app."),
    ("Bike Helmet Adults", 39.99, 4.5, "MIPS, 18 vents, adjustable fit."),
    ("Bicycle 21-Speed", 349.99, 4.4, "Mountain, front suspension, disc brakes."),
    ("Bike Lock U-Lock 12mm", 29.99, 4.4, "Hardened steel, 2 keys, bracket."),
    ("Bike Light Set LED", 19.99, 4.3, "USB rechargeable, 500lm front/100 rear."),
    ("Water Bottle Cage", 7.99, 4.2, "Aluminum, standard mount, 2-pack."),
    ("Pump Floor Bike 160psi", 34.99, 4.5, "Dual valve, gauge, cast iron base."),
    ("Swimming Goggles Anti-Fog", 14.99, 4.3, "Silicone seal, UV protection."),
    ("Swim Cap Silicone", 7.99, 4.2, "Adult, waterproof, 3-pack."),
    ("Kickboard Foam EVA", 19.99, 4.3, "Flotation, ergonomic handles."),
    ("Pull Buoy EVA", 12.99, 4.2, "Figure 8 shape, buoyancy."),
    ("Swim Fins Short", 29.99, 4.3, "Silicone, ergonomic, training."),
    ("Snorkel Mask Full Face", 39.99, 4.4, "Panoramic, anti-fog, GoPro mount."),
    ("Snorkel Set Dry Top", 19.99, 4.3, "Silicone mouthpiece, splash guard."),
    ("Wetsuit 3mm Full", 99.99, 4.4, "Neoprene, back zip, flatlock."),
    ("Rash Guard UPF 50+", 29.99, 4.3, "Long sleeve, quick dry, 4-way stretch."),
    ("Surfboard 7ft Foam", 149.99, 4.3, "Soft top, leash, fins included."),
    ("Boogie Board 42\"", 44.99, 4.2, "PE foam, wrist leash, EPS core."),
    ("Stand Up Paddle Board", 399.99, 4.5, "Inflatable, 10'6\", pump, paddle."),
    ("Kayak Inflatable 2-Person", 299.99, 4.4, "PVC, pump, paddles, 600lb capacity."),
    ("Life Jacket Universal", 34.99, 4.4, "USCG approved, neoprene, 30-50lbs."),
    ("Fishing Rod Combo 6'6\"", 49.99, 4.4, "Medium action, reel, line spooled."),
    ("Tackle Box 3600", 24.99, 4.3, "3-drawer, waterproof, partitioned."),
    ("Fishing Lures Kit 50pc", 29.99, 4.4, "Crankbaits, soft plastics, hooks."),
    ("Fishing Line 300yd 10lb", 9.99, 4.3, "Monofilament, clear, abrasion resistant."),
    ("Hiking Poles Pair", 44.99, 4.4, "Telescoping, cork grip, shock absorbing."),
    ("Gaiters Hiking Waterproof", 24.99, 4.3, "Nylon, adjustable strap, size M/L."),
    ("Trekking Poles Carbon Fiber", 79.99, 4.5, "Ultralight 12oz each, anti-shock."),
    ("Crampons Traction 19 Spikes", 29.99, 4.3, "Stainless steel, elastic strap."),
    ("Ice Axe 70cm", 49.99, 4.4, "Steel head, aluminum shaft, leash."),
    ("Climbing Rope 60m", 199.99, 4.5, "Dynamic, 9.8mm, UIAA certified."),
    ("Climbing Harness Adjustable", 89.99, 4.4, "Gear loops, padded waist, size M."),
    ("Climbing Carabiner Set 6", 34.99, 4.4, "D shaped, locking gate, 24kN."),
    ("Chalk Bag with Belt", 19.99, 4.3, "Fleece lined, drawstring, holds 12oz."),
    ("Climbing Shoes Beginner", 79.99, 4.3, "Lace-up, rubber sole, synthetic."),
    ("Bouldering Crash Pad", 149.99, 4.4, "40\"x32\"x4\", foam, carrying straps."),
    ("Yoga Wheel 12\"", 24.99, 4.2, "PVC, textured, max 500lbs."),
    ("Yoga Bolster Round", 39.99, 4.3, "Cotton cover, buckwheat fill, 24\"."),
    ("Meditation Cushion 6\"", 34.99, 4.3, "Buckwheat hull, cotton cover."),
    ("Massage Ball Lacrosse", 9.99, 4.2, "Hard rubber, trigger point therapy."),
    ("Percussion Massage Gun", 79.99, 4.5, "6 speeds, 4 heads, rechargeable."),
    ("Stretching Strap 10 Loop", 14.99, 4.2, "Nylon, 10 loops, non-stretch."),
    ("Posture Corrector Adjustable", 19.99, 4.3, "Neoprene, unisex, adjustable straps."),
    ("Hand Grip Strengthener", 12.99, 4.3, "Adjustable 10-60kg, 5-pack."),
    ("Pull Up Assist Bands", 24.99, 4.4, "Latex, 4 levels, 6\"x12\" to 2\"x32\"."),
    ("Weighted Vest 40lbs", 79.99, 4.4, "Adjustable, mesh, 1lb increments."),
]
for name, price, rating, desc in sports:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Sports & Fitness", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Groceries ----
groceries = [
    ("Organic Green Tea 100pk", 14.99, 4.4, "Certified organic, antioxidant-rich."),
    ("Almonds Roasted Unsalted 1lb", 9.99, 4.5, "Dry roasted, no salt, resealable."),
    ("Dark Chocolate 72% 3.5oz", 4.99, 4.6, "Belgian, single origin, fair trade."),
    ("Extra Virgin Olive Oil 16oz", 12.99, 4.7, "First cold press, glass bottle."),
    ("Organic Honey 12oz", 8.99, 4.5, "Raw, unfiltered, pure."),
    ("Ground Coffee Medium Roast 12oz", 11.99, 4.6, "Arabica, fair trade, freshly roasted."),
    ("Quinoa Organic 2lb", 7.99, 4.5, "Tri-color, pre-rinsed, gluten-free."),
    ("Chia Seeds 1lb", 6.99, 4.4, "Organic, omega-3, high fiber."),
    ("Protein Powder Vanilla 2lb", 34.99, 4.5, "Whey isolate, 25g protein, low sugar."),
    ("Granola Maple Pecan 12oz", 6.99, 4.4, "Whole grain, lightly sweetened, crunchy."),
    ("Mixed Nuts Roasted 2lb", 14.99, 4.5, "Cashews, almonds, pecans, peanuts."),
    ("Peanut Butter Natural 16oz", 7.99, 4.6, "Creamy, no added sugar, salt."),
    ("Trail Mix 1lb", 8.99, 4.4, "Dried fruit, nuts, M&Ms."),
    ("Dried Mango Slices 8oz", 5.99, 4.3, "Sweetened, chewy, no GMOs."),
    ("Coconut Chips Toasted 4oz", 4.49, 4.3, "Unsweetened, organic, crunchy."),
    ("Rice Jasmine 5lb", 6.99, 4.5, "Long grain, fragrant, Thailand."),
    ("Pasta Penne 1lb 3-pack", 5.99, 4.4, "Italian durum wheat, bronze cut."),
    ("Pasta Sauce Marinara 24oz", 4.99, 4.5, "Imported tomatoes, basil, garlic."),
    ("Canned Tomatoes San Marzano 28oz", 3.99, 4.6, "Whole peeled, DOP certified."),
    ("Tomato Paste 6oz 3-pack", 3.49, 4.4, "Double concentrated, Italian."),
    ("Coconut Milk 13.5oz 4-pack", 7.99, 4.5, "Full fat, BPA-free cans."),
    ("Black Beans Canned 15oz 6-pack", 6.99, 4.4, "Low sodium, organic."),
    ("Chickpeas Canned 15oz 6-pack", 6.99, 4.4, "Organic, no preservatives."),
    ("Lentils Green 2lb", 4.99, 4.5, "Organic, dried, protein rich."),
    ("Oats Rolled 5lb", 7.99, 4.6, "Organic, whole grain, gluten-free."),
    ("Cereal Honey Oat 12oz", 5.99, 4.4, "Whole grain, lightly sweetened."),
    ("Greek Yogurt Plain 32oz", 6.99, 4.5, "Strained, 20g protein, probiotic."),
    ("Butter Unsalted 16oz", 5.99, 4.5, "Cream from grass fed cows."),
    ("Cheddar Cheese Sharp 8oz", 4.99, 4.6, "Aged 2 years, Wisconsin."),
    ("Mozzarella Fresh 8oz", 4.49, 4.5, "Buffalo milk, packed in brine."),
    ("Parmesan Wheel 1lb", 14.99, 4.7, "Aged 24 months, Italy."),
    ("Eggs Free Range 12ct", 5.99, 4.6, "Pasture raised, omega-3."),
    ("Chicken Breast Organic 1lb", 9.99, 4.5, "Boneless, skinless, air chilled."),
    ("Ground Beef 85/15 1lb", 6.99, 4.4, "Grass fed, no antibiotics."),
    ("Salmon Fillet 8oz", 11.99, 4.6, "Wild caught, skin on, center cut."),
    ("Shrimp Raw 21/25 1lb", 12.99, 4.5, "Peeled, deveined, frozen."),
    ("Bread Sourdough Loaf", 4.99, 4.5, "Artisan, naturally leavened."),
    ("Tortilla Chips Corn 12oz", 3.99, 4.3, "Stone ground, organic, sea salt."),
    ("Salsa Verde 16oz", 4.49, 4.4, "Tomatillo, cilantro, jalapeño."),
    ("Hummus Classic 10oz", 4.99, 4.5, "Chickpea, tahini, olive oil."),
    ("Pita Bread 6-pack", 3.99, 4.4, "Whole wheat, pocket style."),
    ("Olives Kalamata 12oz", 6.99, 4.4, "Pitted, Greek, in brine."),
    ("Capers 8oz", 4.99, 4.3, "Non-pareil, packed in vinegar."),
    ("Artichoke Hearts Marinated 12oz", 5.99, 4.3, "Grilled, olive oil, herbs."),
    ("Sun Dried Tomatoes 8oz", 5.49, 4.4, "In olive oil, Italian."),
    ("Balsamic Vinegar 8oz", 7.99, 4.5, "Aged 12 years, Modena."),
    ("Apple Cider Vinegar 16oz", 4.99, 4.4, "Raw, unfiltered, with mother."),
    ("Soy Sauce 20oz", 4.49, 4.5, "Brewed, low sodium."),
    ("Sriracha Hot Sauce 17oz", 4.99, 4.5, "Original, chili garlic."),
    ("Maple Syrup Pure 8oz", 9.99, 4.6, "Grade A amber, Vermont."),
    ("Coconut Oil Organic 16oz", 8.99, 4.5, "Virgin, cold pressed."),
    ("Vanilla Extract Pure 4oz", 12.99, 4.6, "Madagascar bourbon."),
    ("Cinnamon Ground 4oz", 4.99, 4.4, "Ceylon, organic."),
    ("Turmeric Ground 4oz", 5.99, 4.3, "Organic, high curcumin."),
    ("Black Peppercorns 6oz", 5.99, 4.4, "Tellicherry, whole, grinder."),
    ("Sea Salt Flakes 8oz", 6.99, 4.4, "Maldon, pyramid shape."),
    ("Garlic Powder 6oz", 4.49, 4.3, "Organic, granulated."),
    ("Chili Powder 4oz", 3.99, 4.3, "Ancho chipotle blend."),
    ("Italian Seasoning 2oz", 3.99, 4.3, "Oregano, basil, thyme, rosemary."),
    ("Nutritional Yeast 8oz", 7.99, 4.4, "Flakes, vegan, 9g protein."),
    ("Miso Paste White 12oz", 6.99, 4.4, "Organic, fermented soybean."),
    ("Seaweed Snacks 0.35oz 5-pack", 3.99, 4.3, "Roasted, salted, nori."),
    ("Rice Cakes Brown 6-pack", 2.99, 4.2, "Whole grain, lightly salted."),
    ("Popcorn Kernels 2lb", 4.99, 4.4, "Mushroom, organic, non-GMO."),
    ("Crackers Whole Wheat 8oz", 3.99, 4.3, "Sesame, flax, sea salt."),
    ("Cookie Dark Chocolate 5oz", 3.99, 4.5, "Double chocolate, Belgian."),
    ("Gummy Bears 8oz", 3.49, 4.4, "Organic, fruit juice sweetened."),
    ("Frozen Berries Mix 2lb", 9.99, 4.5, "Strawberries, blueberries, raspberries."),
    ("Frozen Broccoli Florets 2lb", 4.99, 4.4, "Organic, steamable bag."),
    ("Frozen Pizza Margherita 12\"", 8.99, 4.4, "Stone fired, mozzarella, basil."),
    ("Ice Cream Vanilla 1qt", 5.99, 4.6, "French style, real vanilla bean."),
    ("Sorbet Mango 1pt", 4.99, 4.4, "Dairy free, real mango."),
    ("Coffee Beans Ethiopian 12oz", 15.99, 4.6, "Light roast, single origin."),
    ("Green Tea Matcha Powder 4oz", 24.99, 4.7, "Ceremonial grade, stone ground."),
    ("Chai Tea Concentrate 32oz", 5.99, 4.4, "Organic, ginger, cardamom."),
    ("Sparkling Water 12-pack", 5.99, 4.5, "Unflavored, glass bottles."),
    ("Coconut Water 4-pack", 6.99, 4.4, "Pure, no added sugar."),
    ("Bone Broth 32oz", 5.99, 4.4, "Grass fed, pasture raised."),
    ("Tofu Extra Firm 14oz", 2.99, 4.3, "Organic, non-GMO."),
    ("Tempeh Original 8oz", 3.99, 4.3, "Fermented, organic."),
    ("Veggie Burger 4-pack", 5.99, 4.3, "Black bean, quinoa, brown rice."),
    ("Cheese Vegan Shredded 8oz", 4.99, 4.2, "Coconut based, melts."),
    ("Almond Milk Unsweetened 32oz", 4.49, 4.4, "Organic, 40 cal per cup."),
    ("Oat Milk Barista 32oz", 5.49, 4.5, "Creamy, froths well."),
    ("Hot Sauce Smoky Chipotle 8oz", 4.99, 4.4, "Adobo pepper base."),
    ("BBQ Sauce Original 18oz", 4.99, 4.4, "Kansas City style, smoky."),
    ("Mustard Dijon 8oz", 3.99, 4.4, "Imported, white wine."),
    ("Ketchup Organic 20oz", 4.49, 4.4, "No HFCS, vine ripened."),
    ("Mayo Avocado Oil 12oz", 5.99, 4.4, "Whole30, paleo, keto friendly."),
    ("Pickles Dill Spears 24oz", 4.49, 4.3, "Fermented, probiotic."),
    ("Sauerkraut 16oz", 4.99, 4.3, "Raw, fermented, organic."),
    ("Kimchi 16oz", 5.99, 4.4, "Traditional, napa cabbage."),
    ("Kombucha 4-pack", 7.99, 4.4, "Ginger lemon, raw."),
    ("Protein Bar Chocolate 12ct", 23.99, 4.5, "20g protein, no artificial."),
]
for name, price, rating, desc in groceries:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Groceries", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Clothing ----
clothing = [
    ("Cotton T-Shirt Crew Neck", 19.99, 4.4, "100% organic cotton, pre-shrunk."),
    ("Denim Jeans Slim Fit", 49.99, 4.4, "Stretch denim, 5-pocket, mid rise."),
    ("Hoodie Fleece Pullover", 44.99, 4.5, "Cotton blend, kangaroo pocket."),
    ("Running Shorts 7\"", 29.99, 4.3, "Moisture wicking, built-in brief."),
    ("Yoga Leggings High Waist", 39.99, 4.6, "4-way stretch, squat proof."),
    ("Sports Bra Medium Support", 29.99, 4.4, "Racerback, moisture wicking."),
    ("Jacket Waterproof Shell", 119.99, 4.5, "2-layer, taped seams, hood."),
    ("Raincoat Lightweight", 59.99, 4.3, "Packable, waterproof 10k."),
    ("Winter Parka Insulated", 199.99, 4.6, "Down fill 650, hood, 30F."),
    ("Fleece Jacket Zip-Up", 49.99, 4.4, "Microfleece, anti-pill."),
    ("Puffer Vest Quilted", 69.99, 4.3, "Synthetic down, packable."),
    ("Casual Button Down Shirt", 34.99, 4.4, "Oxford cloth, button down collar."),
    ("Chino Pants Slim", 44.99, 4.4, "Cotton twill, chino fit."),
    ("Polo Shirt Pique", 34.99, 4.4, "Cotton pique, 2-button placket."),
    ("Dress Shirt Wrinkle Free", 39.99, 4.3, "Cotton, spread collar, slim."),
    ("Blazer Unstructured", 129.99, 4.4, "Italian wool, 2-button."),
    ("Suit Separates 2-Piece", 249.99, 4.5, "Worsted wool, notch lapel."),
    ("Tie Silk 7cm", 29.99, 4.3, "Self-tie, lined, woven."),
    ("Dress Socks 6-Pack", 19.99, 4.4, "Cotton blend, reinforced toe."),
    ("Belt Leather 1.5\"", 34.99, 4.4, "Full grain, brass buckle."),
    ("Casual Sneakers Canvas", 44.99, 4.4, "Rubber sole, canvas upper."),
    ("Boots Leather Chelsea", 149.99, 4.5, "Waxed leather, elastic side."),
    ("Sandals Slide 2-Strap", 24.99, 4.3, "EVA, arch support."),
    ("Formal Oxford Shoes", 119.99, 4.5, "Leather, Goodyear welted."),
    ("Loafers Suede", 89.99, 4.4, "Moccasin style, rubber sole."),
    ("Swim Trunks 9\"", 29.99, 4.3, "Quick dry, mesh liner."),
    ("Bikini Set Triangle", 34.99, 4.3, "Nylon blend, adjustable."),
    ("One Piece Swimsuit", 49.99, 4.4, "Moderate cut, UPF 50."),
    ("Cover Up Kimono 3/4 Sleeve", 29.99, 4.2, "Lightweight, sheer."),
    ("Sun Hat Wide Brim 4\"", 24.99, 4.3, "Straw, UPF 50, packable."),
    ("Beanie Knit Acrylic", 14.99, 4.2, "Ribbed knit, foldable brim."),
    ("Scarf Cashmere Blend 70\"", 39.99, 4.4, "Cashmere mix, fringe."),
    ("Gloves Touchscreen", 19.99, 4.3, "Knitted, conductive fingers."),
    ("Umbrella Windproof Auto", 24.99, 4.3, "Reinforced frame, 42\" arc."),
    ("Backpack 25L Casual", 49.99, 4.4, "Canvas, padded laptop sleeve."),
    ("Tote Bag Canvas 15\"x17\"", 29.99, 4.3, "Cotton, reinforced handles."),
    ("Messenger Bag 15\"", 59.99, 4.4, "Waxed canvas, shoulder strap."),
    ("Crossbody Bag Small", 34.99, 4.3, "Genuine leather, adjustable."),
    ("Wallet Bifold Leather", 39.99, 4.5, "Full grain, RFID block."),
    ("Card Holder Slim 4-Slot", 19.99, 4.4, "Minimalist, leather."),
    ("Watch Analog Stainless", 89.99, 4.5, "Japanese quartz, date window."),
    ("Leather Watch Band 20mm", 24.99, 4.3, "Quick release, brown."),
    ("Sunglasses Aviator", 39.99, 4.4, "Polarized, UV400, metal frame."),
    ("Reading Glasses +2.0", 19.99, 4.3, "Lightweight, spring hinge."),
    ("Blue Light Blocking Glasses", 24.99, 4.3, "Computer, clear lens."),
    ("Bracelet Leather Beaded", 14.99, 4.2, "Natural stone, adjustable."),
    ("Necklace Pendant Silver 18\"", 29.99, 4.3, "Sterling silver, cubic zirconia."),
    ("Earrings Stud 6mm Pearl", 24.99, 4.4, "Freshwater pearl, 14k gold."),
    ("Ring Sterling Silver Band", 19.99, 4.3, "Curb chain style, 6mm."),
    ("Hair Clip Claw Large", 8.99, 4.3, "Acetate, tortoise shell."),
    ("Scrunchie Set 8", 7.99, 4.2, "Silk, velvet, faux fur."),
    ("Headband Knotted 4-pack", 11.99, 4.2, "Cotton, elastic back."),
    ("Baseball Cap Dad Style", 19.99, 4.3, "Cotton twill, pre-curved brim."),
    ("Bucket Hat Packable", 22.99, 4.2, "Nylon, UPF 50, chin strap."),
    ("Winter Beanie Fleece Lined", 17.99, 4.3, "Acrylic wool, windproof."),
    ("Boot Socks Wool 3-Pack", 24.99, 4.4, "Merino blend, cushion sole."),
    ("Ankle Socks No Show 10-Pack", 14.99, 4.3, "Cotton, silicone heel grip."),
    ("Compression Socks 15-20mmHg", 19.99, 4.4, "Graduated, knee high."),
    ("Pajama Set Cotton", 34.99, 4.4, "Long sleeve, button down."),
    ("Robe Plush 58\"", 44.99, 4.5, "Microfiber, shawl collar."),
    ("Slippers Memory Foam", 24.99, 4.3, "Indoor/outdoor sole."),
    ("Boxer Briefs 4-Pack", 24.99, 4.4, "Cotton spandex, moisture wick."),
    ("Underwear Hipster 5-Pack", 19.99, 4.3, "Cotton, tagless."),
    ("Bra T-shirt Lightly Lined", 24.99, 4.3, "Smooth cup, adjustable straps."),
    ("Bralette Lace Triangle", 19.99, 4.2, "Wireless, stretch lace."),
    ("Shapewear Bodysuit", 34.99, 4.3, "Medium control, adjustable straps."),
    ("Tank Top Ribbed 3-Pack", 24.99, 4.4, "Cotton spandex, fitted."),
    ("Graphic Tee Vintage Logo", 24.99, 4.3, "Soft cotton, pre-washed."),
    ("Flannel Shirt Plaid", 39.99, 4.4, "Brushed cotton, button cuffs."),
    ("Denim Jacket Classic", 79.99, 4.5, "100% cotton, button front."),
    ("Leather Jacket Moto", 199.99, 4.5, "Genuine leather, zip front."),
    ("Cardigan Knit Button Front", 49.99, 4.4, "Merino wool, roomy fit."),
    ("Sweater Crew Neck Cashmere", 129.99, 4.6, "100% cashmere, 12gg."),
    ("Vest Puffer Quilted", 59.99, 4.3, "Nylon, down alternative."),
    ("Cargo Pants Multi Pocket", 44.99, 4.3, "Cotton twill, elastic cuffs."),
    ("Joggers Fleece 2-Pocket", 34.99, 4.4, "Cotton poly, elastic waist."),
    ("Track Pants Side Stripe", 29.99, 4.3, "Polyester, zip pockets."),
    ("Mini Skirt A-Line", 34.99, 4.3, "Cotton denim, 5-pocket."),
    ("Midi Skirt Pleated", 44.99, 4.4, "Polyester, elastic waist."),
    ("Maxi Skirt Floral", 39.99, 4.3, "Rayon, tiered ruffle."),
    ("Dress Shirt Relaxed Fit", 34.99, 4.3, "Cotton, button down collar."),
    ("Little Black Dress", 59.99, 4.5, "Knit, scoop neck, 36\""),
    ("Maxi Dress Casual", 49.99, 4.4, "Cotton blend, adjustable straps."),
    ("Sundress Floral Print", 39.99, 4.4, "Lightweight, smocked top."),
    ("Jumpsuit Casual Wide Leg", 54.99, 4.4, "Rayon spandex, wrap style."),
    ("Romper Short Sleeve", 34.99, 4.3, "Cotton poplin, elastic waist."),
    ("Tuxedo Jacket Peak Lapel", 299.99, 4.5, "Worsted wool, satin trim."),
    ("Vest Waistcoat 3-Button", 79.99, 4.3, "Cotton pique, adjustable back."),
    ("Cummerbund Pleated", 29.99, 4.2, "Satin finish, adjustable."),
    ("Bow Tie Pre-Tied", 19.99, 4.3, "Black satin, adjustable band."),
    ("Pocket Square Set 3", 14.99, 4.3, "White, linen, puff fold."),
    ("Suspenders Elastic Clip-On", 16.99, 4.2, "Adjustable, 1.5\" wide."),
    ("Rain Boots 16\"", 59.99, 4.4, "Rubber, pull-on, tread sole."),
    ("Snow Boots Insulated", 99.99, 4.5, "Waterproof, -20F rated."),
    ("Hiking Boots Waterproof", 129.99, 4.5, "Gore-Tex, Vibram sole."),
    ("Work Boots Steel Toe", 149.99, 4.6, "Full grain, slip resistant."),
    ("Slip On Shoes Canvas", 34.99, 4.3, "Rubber, no lace."),
    ("Espadrilles Wedge 3\"", 44.99, 4.3, "Canvas, jute wrap."),
    ("Heels Pumps 4\"", 59.99, 4.4, "Patent, pointed toe."),
    ("Flats Ballerina Bow", 34.99, 4.3, "Leather, cushioned insole."),
    ("Wedges Cork 5\"", 49.99, 4.3, "Leather upper, espadrille."),
    ("Boots Ankle Zip", 89.99, 4.4, "Side zip, stacked heel."),
]
for name, price, rating, desc in clothing:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Clothing", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Books ----
books = [
    ("Clean Code", 39.99, 4.7, "Robert C. Martin. A handbook of agile software craftsmanship."),
    ("The Pragmatic Programmer", 44.99, 4.7, "Hunt & Thomas. Timeless tips for software engineers."),
    ("Design Patterns", 44.99, 4.6, "Gang of Four. Reusable OOP design patterns."),
    ("Introduction to Algorithms", 79.99, 4.7, "CLRS. Comprehensive algorithmic reference."),
    ("Python Crash Course", 29.99, 4.6, "Eric Matthes. Hands-on Python for beginners."),
    ("Fluent Python", 49.99, 4.7, "Luciano Ramalho. Pythonic thinking."),
    ("Deep Learning", 59.99, 4.5, "Goodfellow, Bengio, Courville. MIT Press."),
    ("Artificial Intelligence A Modern Approach", 79.99, 4.6, "Russell & Norvig. Comprehensive AI text."),
    ("The Art of War", 9.99, 4.5, "Sun Tzu. Ancient military strategy classic."),
    ("Sapiens", 18.99, 4.7, "Yuval Noah Harari. A brief history of humankind."),
    ("Thinking Fast and Slow", 14.99, 4.6, "Daniel Kahneman. Behavioral psychology."),
    ("Atomic Habits", 16.99, 4.8, "James Clear. Tiny changes remarkable results."),
    ("1984", 9.99, 4.6, "George Orwell. Dystopian social science fiction."),
    ("To Kill a Mockingbird", 12.99, 4.7, "Harper Lee. Racial injustice in the South."),
    ("The Great Gatsby", 11.99, 4.5, "F Scott Fitzgerald. Jazz Age American classic."),
    ("Dune", 14.99, 4.6, "Frank Herbert. Sci-fi epic set on Arrakis."),
    ("The Lord of the Rings", 19.99, 4.8, "JRR Tolkien. Epic high fantasy trilogy."),
    ("Harry Potter Box Set", 59.99, 4.9, "JK Rowling. Complete 7-book series."),
    ("The Hobbit", 14.99, 4.7, "JRR Tolkien. Bilbo Baggins adventure."),
    ("Gone Girl", 12.99, 4.4, "Gillian Flynn. Psychological thriller."),
    ("The Martian", 13.99, 4.6, "Andy Weir. Astronaut stranded on Mars."),
    ("Educated", 14.99, 4.5, "Tara Westover. Memoir of self-invention."),
    ("Born a Crime", 14.99, 4.6, "Trevor Noah. Stories from a South African childhood."),
    ("Becoming", 16.99, 4.6, "Michelle Obama. Memoir by former First Lady."),
    ("The Alchemist", 13.99, 4.5, "Paulo Coelho. Following your dreams."),
    ("Rich Dad Poor Dad", 11.99, 4.4, "Robert Kiyosaki. Financial literacy."),
    ("The 7 Habits of Highly Effective People", 16.99, 4.6, "Stephen Covey. Personal effectiveness."),
    ("How to Win Friends and Influence People", 14.99, 4.5, "Dale Carnegie. Interpersonal skills."),
    ("The Lean Startup", 18.99, 4.5, "Eric Ries. Entrepreneurship methodology."),
    ("Zero to One", 14.99, 4.5, "Peter Thiel. Notes on startups."),
    ("Good to Great", 19.99, 4.5, "Jim Collins. Company performance study."),
    ("The Hard Thing About Hard Things", 17.99, 4.5, "Ben Horowitz. Building startups."),
    ("Hooked", 14.99, 4.4, "Nir Eyal. Building habit-forming products."),
    ("The Mom Test", 14.99, 4.6, "Rob Fitzpatrick. Customer conversations."),
    ("Rework", 12.99, 4.4, "Fried & Hansson. Business simplification."),
    ("Meditations", 11.99, 4.6, "Marcus Aurelius. Stoic philosophy."),
    ("Man's Search for Meaning", 11.99, 4.7, "Viktor Frankl. Holocaust survival and meaning."),
    ("The Power of Habit", 13.99, 4.5, "Charles Duhigg. Habit formation science."),
    ("Outliers", 14.99, 4.5, "Malcolm Gladwell. Stories of success."),
    ("Blink", 13.99, 4.4, "Malcolm Gladwell. Snap judgments."),
    ("Freakonomics", 14.99, 4.4, "Levitt & Dubner. Economics of everyday."),
    ("Predictably Irrational", 13.99, 4.4, "Dan Ariely. Behavioral economics."),
    ("Misbehaving", 15.99, 4.4, "Richard Thaler. Behavioral economics."),
    ("Nudge", 14.99, 4.3, "Thaler & Sunstein. Decision architecture."),
    ("The Black Swan", 16.99, 4.3, "Nassim Taleb. Highly improbable events."),
    ("Fooled by Randomness", 15.99, 4.3, "Nassim Taleb. Luck and probability."),
    ("Antifragile", 17.99, 4.4, "Nassim Taleb. Things that gain from disorder."),
    ("The Tipping Point", 14.99, 4.4, "Malcolm Gladwell. Social epidemics."),
    ("Guns Germs and Steel", 16.99, 4.5, "Jared Diamond. Human history."),
    ("Cosmos", 18.99, 4.6, "Carl Sagan. The universe unveiled."),
    ("Brief History of Time", 14.99, 4.6, "Stephen Hawking. Cosmology for everyone."),
    ("The Selfish Gene", 15.99, 4.6, "Richard Dawkins. Evolutionary biology."),
    ("The Gene Machine", 13.99, 4.4, "Venki Ramakrishnan. Ribosome discovery."),
    ("Genome", 15.99, 4.4, "Matt Ridley. 23 chromosomes."),
    ("DNA", 14.99, 4.4, "James Watson. Discovery of DNA structure."),
    ("Influence", 15.99, 4.6, "Robert Cialdini. Psychology of persuasion."),
    ("Made to Stick", 13.99, 4.4, "Heath brothers. Why ideas survive."),
    ("The Design of Everyday Things", 19.99, 4.6, "Don Norman. Product design principles."),
    ("Don't Make Me Think", 34.99, 4.6, "Steve Krug. Web usability."),
    ("100 Year Language", 34.99, 4.5, "Benjamin Chelf. Programming language design."),
    ("Structure and Interpretation", 59.99, 4.6, "SICP classic computer science text."),
    ("Code Complete", 44.99, 4.7, "Steve McConnell. Software construction."),
    ("Refactoring", 44.99, 4.5, "Martin Fowler. Improving existing code."),
    ("Working Effectively with Legacy Code", 44.99, 4.5, "Michael Feathers. Legacy code techniques."),
    ("Test Driven Development", 39.99, 4.5, "Kent Beck. TDD by example."),
    ("Domain Driven Design", 44.99, 4.5, "Eric Evans. Software model design."),
    ("Microservices Patterns", 44.99, 4.4, "Chris Richardson. Microservice architecture."),
    ("Designing Data Intensive Applications", 49.99, 4.7, "Martin Kleppmann. Data systems."),
    ("System Design Interview", 39.99, 4.6, "Alex Xu. Interview prep."),
    ("Cracking the Coding Interview", 34.99, 4.5, "Gayle Laakmann McDowell. Tech interviews."),
    ("Algorithms 4th Edition", 59.99, 4.6, "Sedgewick & Wayne. Algorithms in Java."),
    ("Computer Networking Top Down", 69.99, 4.5, "Kurose & Ross. Networking fundamentals."),
    ("Operating Systems Three Easy Pieces", 49.99, 4.6, "Remzi & Andrea Arpaci-Dusseau. OS."),
    ("The Phoenix Project", 16.99, 4.5, "Gene Kim. DevOps novel."),
    ("The Goal", 19.99, 4.5, "Eliyahu Goldratt. Theory of constraints."),
    ("Measure What Matters", 17.99, 4.4, "John Doerr. OKR framework."),
    ("Start With Why", 15.99, 4.4, "Simon Sinek. Inspiring leadership."),
    ("Leaders Eat Last", 16.99, 4.4, "Simon Sinek. Team leadership."),
    ("Drive", 14.99, 4.4, "Daniel Pink. Motivation science."),
    ("Grit", 14.99, 4.5, "Angela Duckworth. Power of passion."),
    ("Mindset", 14.99, 4.5, "Carol Dweck. Growth psychology."),
    ("Daring Greatly", 14.99, 4.5, "Brené Brown. Vulnerability courage."),
    ("Braving the Wilderness", 14.99, 4.4, "Brené Brown. True belonging."),
    ("The Gifts of Imperfection", 13.99, 4.4, "Brené Brown. Letting go of who you should be."),
    ("The Subtle Art of Not Giving a F*ck", 16.99, 4.5, "Mark Manson. Counterintuitive living."),
    ("Everything Is F*cked", 16.99, 4.3, "Mark Manson. Hope and meaning."),
    ("Ikigai", 12.99, 4.5, "Héctor García. Japanese secret to long life."),
    ("Deep Work", 15.99, 4.6, "Cal Newport. Focused success."),
    ("So Good They Can't Ignore You", 14.99, 4.4, "Cal Newport. Career advice."),
    ("Digital Minimalism", 14.99, 4.4, "Cal Newport. Technology philosophy."),
    ("The 4 Hour Work Week", 15.99, 4.3, "Tim Ferriss. Lifestyle design."),
    ("Tools of Titans", 24.99, 4.4, "Tim Ferriss. Wisdom and tactics."),
    ("The War of Art", 12.99, 4.5, "Steven Pressfield. Creative resistance."),
    ("Do the Work", 11.99, 4.4, "Steven Pressfield. Overcoming procrastination."),
    ("Big Magic", 14.99, 4.4, "Elizabeth Gilbert. Creative living."),
    ("Gödel Escher Bach", 19.99, 4.5, "Douglas Hofstadter. Strange loops."),
    ("Flatland", 11.99, 4.4, "Edwin Abbott. Dimensional satire."),
    ("Surely You're Joking Mr Feynman", 14.99, 4.6, "Richard Feynman. Physicist memoirs."),
    ("The Science of Interstellar", 19.99, 4.4, "Kip Thorne. Black hole science."),
    ("Elegant Universe", 16.99, 4.5, "Brian Greene. String theory."),
    ("Hyperspace", 14.99, 4.4, "Michio Kaku. Higher dimensions."),
    ("Physics for Future Presidents", 16.99, 4.4, "Richard Muller. Physics for non-scientists."),
    ("The Code Book", 16.99, 4.5, "Simon Singh. Cryptography history."),
]
for name, price, rating, desc in books:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Books", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Beauty & Personal Care ----
beauty = [
    ("Moisturizer Face 1.7oz", 24.99, 4.5, "Hyaluronic acid, SPF 30, daily."),
    ("Sunscreen SPF 50 3oz", 19.99, 4.5, "Mineral, zinc oxide, reef safe."),
    ("Lip Balm SPF 30 2-pack", 7.99, 4.4, "Moisturizing, coconut oil base."),
    ("Face Serum Vitamin C 1oz", 29.99, 4.6, "Antioxidant, brightening."),
    ("Retinol Cream 1.7oz", 34.99, 4.5, "Anti-aging, night repair."),
    ("Eye Cream 0.5oz", 22.99, 4.4, "Caffeine, peptides, dark circles."),
    ("Niacinamide Serum 10% 1oz", 19.99, 4.5, "Pore reducing, oil control."),
    ("Cleanser Gel Foaming 6oz", 16.99, 4.4, "Gentle, pH balanced."),
    ("Toner Alcohol Free 8oz", 14.99, 4.4, "Rose water, witch hazel."),
    ("Exfoliating Scrub 4oz", 12.99, 4.3, "Physical, jojoba beads."),
    ("Sheet Mask Set 10", 14.99, 4.4, "Hydrating, collagen."),
    ("Face Wash Clay 5oz", 13.99, 4.4, "Kaolin clay, deep clean."),
    ("Shampoo Volumizing 12oz", 14.99, 4.4, "Biotin, sulfate free."),
    ("Conditioner Smoothing 12oz", 14.99, 4.4, "Argan oil, keratin."),
    ("Hair Mask Deep Conditioning 8oz", 19.99, 4.5, "Coconut, shea butter."),
    ("Hair Oil Treatment 4oz", 16.99, 4.4, "Argan oil, frizz control."),
    ("Dry Shampoo 5oz", 9.99, 4.3, "Rice starch, no residue."),
    ("Hair Spray Strong Hold 10oz", 11.99, 4.3, "Flexible, non-sticky."),
    ("Body Lotion 16oz", 12.99, 4.4, "Shea butter, cocoa."),
    ("Body Wash 16oz", 11.99, 4.4, "Lavender, moisturizing."),
    ("Hand Cream 2oz", 8.99, 4.4, "Aloe vera, fast absorbing."),
    ("Foot Cream 4oz", 9.99, 4.3, "Peppermint, cooling."),
    ("Deodorant Natural 2.5oz", 10.99, 4.3, "Aluminum free, coconut oil."),
    ("Perfume Eau de Parfum 1.7oz", 59.99, 4.5, "Floral, woody, long lasting."),
    ("Cologne 3.4oz", 49.99, 4.4, "Citrus, aquatic, fresh."),
    ("Makeup Brush Set 12pc", 24.99, 4.4, "Synthetic bristles, case."),
    ("Foundation Liquid 1oz", 29.99, 4.4, "Full coverage, SPF 15."),
    ("Concealer Stick 0.2oz", 14.99, 4.4, "Full coverage, creamy."),
    ("Setting Powder Translucent 0.8oz", 22.99, 4.5, "Lightweight, oil control."),
    ("Blush Powder 0.15oz", 19.99, 4.3, "Pigmented, buildable."),
    ("Bronzer Powder 0.35oz", 22.99, 4.4, "Matte, warm tone."),
    ("Highlighter Stick 0.2oz", 18.99, 4.4, "Creamy, dewy finish."),
    ("Eyeshadow Palette 12 Colors", 34.99, 4.5, "Matte, shimmer, blendable."),
    ("Eyeliner Liquid 0.04oz", 12.99, 4.4, "Waterproof, fine tip."),
    ("Mascara Volume 0.3oz", 16.99, 4.5, "Lengthening, waterproof."),
    ("Eyebrow Pencil 0.01oz", 11.99, 4.3, "Fine tip, spoolie brush."),
    ("Lipstick Matte 0.12oz", 18.99, 4.4, "Long wear, creamy."),
    ("Lip Gloss 0.15oz", 14.99, 4.3, "Shiny, non-sticky."),
    ("Lip Liner 0.04oz", 9.99, 4.3, "Precision tip, long lasting."),
    ("Nail Polish 0.5oz 6-pack", 19.99, 4.3, "Gel finish, chip resistant."),
    ("Nail File Set 7pc", 8.99, 4.2, "Glass, metal, wood."),
    ("Cuticle Oil 0.5oz", 7.99, 4.3, "Vitamin E, jojoba."),
    ("Nail Polish Remover 8oz", 5.99, 4.3, "Acetone free."),
    ("Cotton Rounds 100ct", 4.99, 4.3, "Organic, biodegradable."),
    ("Facial Tissue 6-pack", 14.99, 4.4, "Lotion infused, 100ct."),
    ("Q-Tips Cotton 500ct", 5.99, 4.4, "Paper stem, pure cotton."),
    ("Makeup Remover Wipes 25ct", 5.99, 4.4, "Micellar, no rinse."),
    ("Micellar Water 13.5oz", 10.99, 4.4, "Gentle, no alcohol."),
    ("Toner Pads BHA 60ct", 16.99, 4.4, "Exfoliating, salicylic."),
    ("Lip Sleeping Mask 0.7oz", 14.99, 4.5, "Berry, overnight repair."),
    ("Under Eye Patches 30ct", 12.99, 4.3, "Hydrogel, gold."),
    ("Facial Roller Jade", 12.99, 4.2, "Natural jade, massage."),
    ("Face Steamer 2-in-1", 29.99, 4.3, "Nano ionic, warm mist."),
    ("LED Face Mask Light Therapy", 79.99, 4.4, "Red, blue light, 7 colors."),
    ("Tweezers Slant Tip", 9.99, 4.4, "Stainless steel, precision."),
    ("Scissors Cuticle 4\"", 7.99, 4.3, "Curved blade, sharp tip."),
    ("Nail Clipper Set 3pc", 6.99, 4.3, "Stainless, non-slip grip."),
    ("Hair Brush Paddle", 12.99, 4.3, "Cushion base, detangler."),
    ("Hair Comb Wide Tooth", 6.99, 4.2, "Acetate, anti-static."),
    ("Curling Iron 1\"", 29.99, 4.4, "Ceramic, adjustable heat."),
    ("Flat Iron Straightener 1\"", 34.99, 4.4, "Tourmaline, 450°F."),
    ("Hot Brush Round 1.5\"", 24.99, 4.3, "Volumizing, nylon bristles."),
    ("Electric Razor Women's", 29.99, 4.3, "Wet/dry, LED light."),
    ("Epilator Cordless", 49.99, 4.3, "Multiple speed, massage cap."),
    ("Wax Strips Ready 40ct", 8.99, 4.3, "Facial, body, sensitive."),
    ("Bath Bombs Set 12", 24.99, 4.4, "Essential oils, fizzing."),
    ("Bath Salt Epsom 5lb", 14.99, 4.4, "Magnesium, lavender."),
    ("Shower Steamers 6-pack", 12.99, 4.3, "Eucalyptus, aromatherapy."),
    ("Essential Oil Set 6", 19.99, 4.4, "Lavender, peppermint, tea tree."),
    ("Aromatherapy Diffuser", 29.99, 4.5, "Ultrasonic, LED, 300ml."),
    ("Massage Oil 8oz", 14.99, 4.3, "Unscented, jojoba based."),
    ("Soap Bar Set 4", 12.99, 4.4, "Olive oil, oatmeal."),
    ("Loofah Natural 3-pack", 7.99, 4.3, "Plant based, exfoliating."),
    ("Body Scrub Sugar 12oz", 14.99, 4.4, "Brown sugar, vanilla."),
    ("Hand Sanitizer 8oz", 6.99, 4.3, "62% alcohol, aloe vera."),
    ("Sunscreen Stick SPF 50", 11.99, 4.4, "Clear, water resistant."),
    ("Lip Balm Tinted 0.15oz", 12.99, 4.4, "Sheer color, SPF 20."),
    ("BB Cream SPF 35 1.5oz", 24.99, 4.4, "Light coverage, moisturizing."),
    ("CC Cream SPF 50 1.5oz", 26.99, 4.4, "Color correcting, anti-aging."),
    ("Primer Face 1oz", 24.99, 4.4, "Pore minimizing, smoothing."),
    ("Setting Spray 2oz", 16.99, 4.4, "Matte finish, 16hr hold."),
    ("Makeup Sponge Set 4", 8.99, 4.3, "Soft, latex-free."),
    ("Brush Cleaner Spray 4oz", 9.99, 4.3, "Quick drying, sanitizing."),
    ("Eyelash Curler", 8.99, 4.3, "Stainless, silicone pad."),
    ("False Lashes 5-Pack", 12.99, 4.3, "Natural, wispy, lash glue."),
    ("Lash Glue 0.15oz", 5.99, 4.2, "Clear, latex-free, long hold."),
    ("Hair Wax Stick 0.6oz", 7.99, 4.2, "Smoothing, flyaway control."),
    ("Pomade Strong Hold 3oz", 12.99, 4.3, "Matte finish, water based."),
    ("Hair Gel 6oz", 8.99, 4.2, "Extra hold, no flaking."),
    ("Sea Salt Spray 8oz", 11.99, 4.3, "Texturizing, beach waves."),
    ("Heat Protectant 8oz", 10.99, 4.4, "Spray, up to 450°F."),
    ("Leave In Conditioner 8oz", 12.99, 4.4, "Detangling, nourishing."),
    ("Hair Perfume 1.7oz", 24.99, 4.3, "Light mist, floral scent."),
    ("Scalp Massager Silicone", 7.99, 4.3, "Stimulation, shampoo brush."),
    ("Travel Bottles Set 4", 7.99, 4.3, "TSA approved, silicone."),
    ("Cosmetic Bag Travel", 14.99, 4.3, "Waterproof, hanging hook."),
    ("Makeup Organizer Acrylic", 19.99, 4.4, "Stackable, 8 compartments."),
    ("Vanity Mirror 10x Magnifying", 24.99, 4.3, "LED, 360° rotation."),
    ("Jewelry Box Velvet 10\"", 29.99, 4.4, "Dividers, lid mirror."),
    ("Watch Box 12-Slot", 34.99, 4.4, "Leather, glass top, lock."),
    ("Sunglasses Case Hard Shell", 12.99, 4.3, "Carbon fiber, microfiber."),
    ("Shaving Cream Sensitive 7oz", 9.99, 4.4, "Aloe, soothing."),
    ("Razor Safety 5-Blade", 14.99, 4.4, "Ergonomic, lubricating strip."),
    ("Shaving Brush Badger Hair", 24.99, 4.3, "Pure badger, wood handle."),
    ("Aftershave Balm 3.4oz", 16.99, 4.4, "Alcohol free, moisturizing."),
    ("Beard Oil 1oz", 14.99, 4.4, "Jojoba, argan, sandalwood."),
    ("Beard Balm 2oz", 12.99, 4.3, "Shea, beeswax, conditioning."),
    ("Beard Comb Sandalwood", 8.99, 4.2, "Handcrafted, wide teeth."),
    ("Beard Trimmer Cordless", 34.99, 4.4, "Adjustable lengths, rechargeable."),
    ("Toothbrush Electric Sonic", 39.99, 4.5, "3 modes, 2min timer."),
    ("Toothbrush Heads 8-Pack", 19.99, 4.4, "Compatible with most brands."),
    ("Whitening Strips 14ct", 24.99, 4.3, "Peroxide free, enamel safe."),
    ("Floss 50m 3-Pack", 7.99, 4.4, "Waxed, shred resistant."),
    ("Mouthwash Alcohol Free 16oz", 7.99, 4.4, "Fluoride, fresh mint."),
]
for name, price, rating, desc in beauty:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Beauty & Personal Care", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

# ---- Automotive ----
automotive = [
    ("Car Wax Carnauba 16oz", 19.99, 4.4, "Brazilian carnauba, deep shine."),
    ("Microfiber Cloth 12-Pack", 14.99, 4.5, "300 GSM, lint free."),
    ("Car Wash Soap 64oz", 12.99, 4.4, "pH balanced, sudsy."),
    ("Wheel Cleaner 32oz", 14.99, 4.3, "Iron removal, acid free."),
    ("Tire Shine Spray 16oz", 9.99, 4.3, "UV protectant, water based."),
    ("Glass Cleaner Automotive 32oz", 8.99, 4.3, "Streak free, ammonia free."),
    ("Interior Detailer 16oz", 11.99, 4.3, "UV protection, matte finish."),
    ("Leather Cleaner 16oz", 12.99, 4.4, "PH neutral, conditioner blend."),
    ("Car Cover All Weather", 69.99, 4.4, "Waterproof, UV resistant."),
    ("Sunshade Windshield 60\"", 17.99, 4.3, "Reflective, foldable."),
    ("Floor Mats All Weather 4pc", 49.99, 4.5, "Heavy duty, custom fit."),
    ("Trunk Mat Liner", 34.99, 4.3, "Rubber, raised edges."),
    ("Seat Covers Set 2", 44.99, 4.3, "Neoprene, airbag compatible."),
    ("Steering Wheel Cover 15\"", 14.99, 4.3, "Leather, non-slip."),
    ("Shift Knob Carbon Fiber", 24.99, 4.2, "Universal fit, weighted."),
    ("Phone Mount Dashboard", 19.99, 4.4, "Magnetic, adhesive pad."),
    ("Phone Mount Vent 2-Arm", 14.99, 4.3, "360° rotation, one touch."),
    ("Car Charger USB 48W", 12.99, 4.4, "Dual USB-C, fast charge."),
    ("Cable Organizer 6-Pack", 7.99, 4.2, "Silicone, self adhesive."),
    ("Air Freshener Vent 3-Pack", 8.99, 4.3, "Essential oil, long lasting."),
    ("Dash Cam Front and Rear", 99.99, 4.5, "4K+1080p, parking mode."),
    ("GPS Navigator 7\"", 149.99, 4.4, "Live traffic, voice."),
    ("Jump Starter 2000A", 79.99, 4.5, "12V, USB, LED light."),
    ("Tire Inflator 12V", 34.99, 4.4, "Digital gauge, auto shut-off."),
    ("Emergency Kit Roadside", 29.99, 4.4, "29-piece, reflective case."),
    ("First Aid Kit Auto 100pc", 19.99, 4.4, "EMT recommended."),
    ("Seat Belt Cutter Window Breaker", 9.99, 4.4, "Spring loaded, carabiner."),
    ("Fire Extinguisher 2.5lb", 24.99, 4.4, "ABC dry chemical, bracket."),
    ("Tire Pressure Gauge Digital", 12.99, 4.4, "0-100 PSI, backlit."),
    ("Tow Strap 20ft 30,000lb", 24.99, 4.4, "Nylon, loop ends."),
    ("Ratchet Straps 4-Pack 15ft", 19.99, 4.4, "1500lb capacity, coated."),
    ("Bungee Cords 10-Pack", 11.99, 4.3, "Mixed sizes, hooks."),
    ("Roof Rack Cross Bars", 89.99, 4.3, "Aluminum, 150lb capacity."),
    ("Cargo Carrier Rooftop 15cuft", 129.99, 4.4, "Hard shell, lockable."),
    ("Bike Rack Trunk 2-Bike", 69.99, 4.3, "Adjustable, padded."),
    ("Hitch Receiver 2\"", 29.99, 4.3, "Class III, 5000lb."),
    ("Hitch Cargo Carrier 500lb", 99.99, 4.4, "Steel, folding."),
    ("Trailer Light Kit LED", 44.99, 4.3, "Submersible, 4-wire."),
    ("Oil Filter Wrench", 12.99, 4.3, "Adjustable, steel band."),
    ("Funnel Set 3-Pack", 7.99, 4.3, "Flexible, colored."),
    ("Drain Pan 16qt", 9.99, 4.3, "Leak proof, spout."),
    ("Jack Stands 3-Ton Pair", 44.99, 4.5, "Ratcheting, pin lock."),
    ("Floor Jack 3-Ton", 89.99, 4.5, "Hydraulic, double pump."),
    ("Tool Set 150-Piece", 59.99, 4.5, "Socket, wrench, bits."),
    ("Socket Set 3/8 Drive 40pc", 39.99, 4.5, "CR-V steel, case."),
    ("Wrench Set Combo 13pc", 29.99, 4.4, "Metric SAE, chrome."),
    ("Pliers Set 5-Piece", 24.99, 4.4, "Linesman, needle, slip joint."),
    ("Screwdriver Set 10pc", 19.99, 4.4, "Magnetic, cushioned grip."),
    ("Hex Key Set Metric 9pc", 9.99, 4.3, "L shape, ball end."),
    ("Torque Wrench 1/2 Drive", 49.99, 4.5, "Click type, 10-150ft.lb."),
    ("Multimeter Automotive", 34.99, 4.4, "AC/DC, resistance, continuity."),
    ("Circuit Tester 6-24V", 9.99, 4.3, "LED, piercing probe."),
    ("Battery Terminal Cleaner", 7.99, 4.2, "Wire brush, 2 ends."),
    ("Battery Charger 12V 8A", 49.99, 4.4, "Automatic, float mode."),
    ("Headlight Restoration Kit", 14.99, 4.3, "3 steps, UV coating."),
    ("Paint Touch Up Kit", 19.99, 4.2, "Base coat, clear coat."),
    ("Rubbing Compound 8oz", 11.99, 4.3, "Heavy cut, scratch remover."),
    ("Polish Machine 10oz", 14.99, 4.4, "Fine cut, swirl remover."),
    ("Applicator Pad Set 4", 8.99, 4.3, "Foam, microfiber."),
    ("Dual Action Polisher", 69.99, 4.5, "Variable speed, 6\" pad."),
    ("Wax Pad 5-Pack", 12.99, 4.3, "Foam, hook and loop."),
    ("Car Vacuum 12V", 34.99, 4.3, "300W, HEPA, attachments."),
    ("Pressure Washer Electric 1800PSI", 99.99, 4.5, "Variable pressure, detergent."),
    ("Foam Cannon 1 quart", 19.99, 4.3, "Adjustable, 1/4\" quick connect."),
    ("Garden Hose 50ft", 24.99, 4.3, "Reinforced, kink resistant."),
    ("Nozzle Spray Gun 7-Pattern", 12.99, 4.4, "Metal, ergonomic grip."),
    ("Bucket 5gal Utility", 7.99, 4.3, "Heavy duty, pour spout."),
    ("Wash Mitt Microfiber", 9.99, 4.4, "Chenille, microbe resistant."),
    ("Drying Towel 36x24\"", 14.99, 4.4, "Waffle weave, 500 GSM."),
    ("Detailing Brush Set 5", 8.99, 4.2, "Soft bristles, precision."),
    ("Clay Bar Kit 200g", 16.99, 4.4, "Clay bar, lubricant, cloth."),
    ("Iron Decontamination Spray 16oz", 18.99, 4.3, "Purple, industrial grade."),
    ("Snow Foam 32oz", 14.99, 4.3, "High suds, citrus scent."),
    ("Tire Dressing Gel 16oz", 12.99, 4.3, "Water based, matte."),
    ("Leather Conditioner 8oz", 14.99, 4.4, "Lanolin, UV protection."),
    ("Carpet Cleaner Machine 8oz", 9.99, 4.3, "Foaming, stain lift."),
    ("Vinyl Protectant 16oz", 10.99, 4.3, "Dashboard, UV block."),
    ("Bug Remover 16oz", 11.99, 4.2, "Biodegradable, citrus."),
    ("Tar Remover 16oz", 12.99, 4.3, "Road tar, asphalt."),
    ("Glass Coating 4oz", 24.99, 4.4, "Hydrophobic, 6 month."),
    ("Ceramic Coating Kit 50ml", 49.99, 4.5, "9H hardness, 2 year."),
    ("Microfiber Towel 12x12\" 20-Pack", 17.99, 4.4, "General purpose, 250 GSM."),
    ("License Plate Frame Black", 8.99, 4.3, "Silicone, no drill."),
    ("LED License Plate Light 2-Pack", 11.99, 4.3, "Canbus, error free."),
    ("LED Interior Lights Kit 4-Pack", 14.99, 4.3, "Dome, map, trunk."),
    ("LED Fog Lights 2-Pack", 29.99, 4.3, "Bright white, universal."),
    ("LED Tail Lights Pair", 59.99, 4.4, "Smoked, plug and play."),
    ("Headlight Bulbs LED 9005", 39.99, 4.4, "12000LM, 6500K, fan."),
    ("Wiper Blades 24\" 2-Pack", 22.99, 4.4, "Beam style, all season."),
    ("Rain Repellent 8oz", 11.99, 4.3, "Glass treatment, 60mph."),
    ("Antenna Short 5\"", 9.99, 4.2, "Carbon fiber, no signal loss."),
    ("Horn Loud 12V 2-Pack", 19.99, 4.3, "High/low tone, relay."),
    ("Mud Flaps Set 4", 24.99, 4.2, "Heavy duty, universal."),
    ("Splash Guards Front Pair", 18.99, 4.2, "Molded, paint matched."),
    ("Fender Flares Black 4pc", 89.99, 4.2, "Rustic, textured."),
    ("Side Steps Nerf Bars 3\"", 149.99, 4.3, "Black, oval, mounting."),
    ("Bed Liner Spray 4gal", 79.99, 4.4, "UV resistant, textured."),
    ("Tonneau Cover Soft 5.5ft", 199.99, 4.4, "Roll up, buckle."),
    ("Tailgate Assist Damper", 29.99, 4.3, "Dual action, easy close."),
    ("Bug Deflector Hood Shield", 39.99, 4.2, "Smoked acrylic."),
    ("Window Vent Visors 4pc", 44.99, 4.3, "In channel, rain guard."),
    ("Dashboard Mat Non Slip", 22.99, 4.2, "Anti glare, custom cut."),
    ("Shift Paddles Extensions", 19.99, 4.2, "Carbon, aluminum."),
    ("Pedal Covers Sport Set 3", 24.99, 4.2, "Aluminum, rubber pads."),
    ("Gas Cap Lock Keyed", 11.99, 4.3, "Universal, tether."),
    ("Window Tint Film 2ftx10ft", 24.99, 4.2, "5% limo, UV block."),
    ("Wrap Vinyl 4ftx5ft Gloss Black", 34.99, 4.3, "Air release, 3M quality."),
    ("Racing Stripe 10ft", 14.99, 4.2, "Vinyl, matte black."),
    ("Emblem Overlay Set", 12.99, 4.2, "Black out, carbon."),
    ("Exhaust Tip 4\" Rolled", 24.99, 4.3, "Stainless, bolt on."),
    ("Cold Air Intake 3\"", 69.99, 4.3, "Aluminum pipe, filter."),
    ("Oil Catch Can Universal", 49.99, 4.3, "Baffled, drain valve."),
    ("Strut Bar Front Upper", 89.99, 4.3, "Aluminum, adjustable."),
    ("Coilover Lowering Kit", 399.99, 4.4, "Adjustable, 32 way."),
    ("Sway Bar 25mm Front", 149.99, 4.3, "Solid, poly bushings."),
    ("Brake Pad Set Ceramic", 49.99, 4.5, "Low dust, quiet."),
    ("Brake Rotors Drilled Slotted 2pc", 119.99, 4.5, "Coated, performance."),
    ("Stainless Brake Lines 4-Pack", 44.99, 4.4, "Teflon liner, DOT."),
    ("Spark Plugs Iridium 4-Pack", 24.99, 4.5, "Fine wire, pre-gapped."),
    ("Ignition Coils Pack 4", 69.99, 4.4, "Direct fit, coil on plug."),
    ("Air Filter High Flow", 39.99, 4.5, "Washable, reusable."),
    ("Cabin Air Filter Activated Charcoal", 19.99, 4.4, "Allergen reduction."),
    ("Oil Filter Premium 1-Pack", 8.99, 4.4, "Synthetic media, 10k miles."),
    ("Oil Change Kit 5qt Mobil 1", 39.99, 4.5, "Full synthetic, filter."),
    ("Transmission Fluid 1qt", 12.99, 4.4, "ATF, synthetic blend."),
    ("Coolant Antifreeze 1gal", 16.99, 4.4, "50/50, universal."),
    ("Power Steering Fluid 16oz", 9.99, 4.3, "Synthetic, stop leak."),
    ("Brake Fluid DOT 4 12oz", 8.99, 4.4, "High boiling, wet 365."),
    ("Windshield Washer Fluid 1gal", 3.99, 4.3, "Bug cleaner, -20°F."),
    ("Fuel Additive 16oz", 11.99, 4.3, "Injector cleaner, ethanol."),
    ("Octane Booster 16oz", 14.99, 4.3, "Race formula, 3 points."),
    ("Diesel Additive 16oz", 15.99, 4.3, "Cetane boost, anti gel."),
    ("Fuel Stabilizer 16oz", 12.99, 4.4, "Storage, ethanol safe."),
    ("Antifreeze Tester Refractometer", 19.99, 4.3, "Glycol, battery."),
    ("Compression Tester Kit", 34.99, 4.4, "Gas diesel, quick connect."),
    ("Vacuum Gauge Set", 24.99, 4.3, "0-30 inHg, boost."),
    ("Timing Light Xenon 12V", 29.99, 4.3, "Inductive, advance."),
    ("Battery Load Tester 12V", 39.99, 4.4, "100A load, digital."),
]
for name, price, rating, desc in automotive:
    stock = random.randint(5, 500)
    products.append({"id": pid, "name": name, "category": "Automotive", "price": price, "rating": rating, "stock": stock, "description": desc})
    pid += 1

print(f"Generated {len(products)} products across {len(set(p['category'] for p in products))} categories")
with open("products.json", "w") as f:
    json.dump(products, f, indent=2)
print("Saved to products.json")
